### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by bjordan2010** [kkapelon/java-testing-with-spock#10]
I have two issues.  I am trying to buy your book on Manning's site and it won't add to my cart.

I am hoping it will help with a problem I am having.  I have a test like this:

import spock.lang.Specification

class EmployeeTest extends Specification {
    def "a valid employee should be valid"() {
        given:
        def Employee employee = new Employee()
        def User mockUser = Mock(User)

```
    when:
    BusinessServiceResult bsResult = employee.prepareForPersistance("aTransactionId", "aTransactionName", mockUser);

    then:
    bsResult != null
    bsResult.isSuccessful()
}
```

}

I get 

groovy.lang.MissingMethodException: No signature of method: com.pbi.datanet.model.businessobject.bo.Employee.prepareForPersistance() is applicable for argument types: (java.lang.String, java.lang.String, com.pbi.datanet.model.businessobject.bo.User$$EnhancerByCGLIB$$20359d67) values: [aTransactionId, aTransactionName, Mock for type 'User' named 'mockUser']
Possible solutions: prepareForPersistence(java.lang.String, java.lang.String, com.pbi.datanet.model.businessobject.bo.User)

but I have seen in your code here that you pass mocks as real objects.  Sorry to leave this here it's the only way I could find to contact you.

**Comment by kkapelon** [comment]
Hello Brian

I will close this issue since it is not really related with the code of the book.

Regarding your questions

1)You should contact Manning at support@manning.com and explain the problem with the cart.
I would also advise to you to post a screenshot of the problem. I cannot really help you with that.

2)Regarding your example, even though I could research it myself it is better if you post it either on stackoverflow (http://stackoverflow.com/questions/tagged/spock) or the official Spock mailing list (https://groups.google.com/forum/#!forum/spockframework) so that other people can see it as well.
It is best if you show the complete code of the Employee class as well.

I would also note that the syntax def Employee employee = new Employee() is slightly confusing.
It should be either Employee employee = new Employee() or def employee = new Employee() 
Probably unrelated with your problem, but good practice nevertheless.

Kostis

**Comment by kkapelon** [comment]
You should also post your Maven or Gradle file so that we can see what dependencies you use. 

Good luck!
